In [1]:
'''
Zachary的空手道俱乐部是一个常用的社交网络，每个节点代表一个空手道俱乐部的成员，
并将他们之间的关系用边来表示。在Zachary学习空手道的时候，管理员和教练发生了冲突，
导致空手道俱乐部一分为二。下图显示了网络的图表示，
节点的标记表示了这个人属于俱乐部的哪个部分。管理员和教练分别用“A”和“I”标记。
'''

'\nZachary的空手道俱乐部是一个常用的社交网络，每个节点代表一个空手道俱乐部的成员，\n并将他们之间的关系用边来表示。在Zachary学习空手道的时候，管理员和教练发生了冲突，\n导致空手道俱乐部一分为二。下图显示了网络的图表示，\n节点的标记表示了这个人属于俱乐部的哪个部分。管理员和教练分别用“A”和“I”标记。\n'

In [26]:
# 构建GCN
# 现在我们来构建这个图卷积网络。
# 实际上，我们不会训练网络，而只是随机初始化它来生成我们在本文开头看到的特征表示。
# 我们将使用 networkx，它有一个现成的俱乐部的图形表示，并很容易计算 A_hat和 D_hat矩阵。
from networkx import karate_club_graph
import networkx as nx
import numpy as np

zkc = karate_club_graph()
order = sorted(list(zkc.nodes()))
A = nx.to_numpy_matrix(zkc, nodelist=order)
I = np.eye(zkc.number_of_nodes())
A_hat = A + I
D_hat = np.array(np.sum(A_hat, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat))

In [27]:
# 接下来，我们随机初始化权值。
W_1 = np.random.normal(loc=0, 
                       scale=1,
                       size=(zkc.number_of_nodes(), 4)
                      )
W_2 = np.random.normal(loc=0,
                       size=(W_1.shape[1], 2))

In [28]:
print(W_1.shape)
print(W_2.shape)

(34, 4)
(4, 2)


In [29]:
# 堆叠GCN层。
# 这里我们只使用单位矩阵作为特征表示，即每个节点都表示为一个类别变量的独热编码。
def relu(x):
    return np.maximum(0, x)
def gcn_layer(A_hat, D_hat, X, W): 
    return relu(D_hat**-1 * A_hat * X * W)
H_1 = gcn_layer(A_hat, D_hat, I, W_1)
print(H_1)
H_2 = gcn_layer(A_hat, D_hat, H_1, W_2)
print(H_2)
output = H_2

[[0.         0.         0.08008562 0.        ]
 [0.04570873 0.         0.21168488 0.19430566]
 [0.29422719 0.         0.22024659 0.08502498]
 [0.         0.         0.35522007 0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.38072236 0.         0.        ]
 [0.         0.         0.11809464 0.        ]
 [0.05882608 0.         0.0195617  0.        ]
 [0.39106676 0.         0.45384391 0.        ]
 [0.         0.         0.27602719 0.        ]
 [0.         0.         1.04069232 0.        ]
 [0.07436321 0.         0.10779006 0.        ]
 [0.         0.         0.314829   0.        ]
 [0.         0.         0.50265271 0.        ]
 [0.         0.1959587  0.59339338 0.        ]
 [0.         0.98040791 0.         0.        ]
 [0.         0.         0.07313805 0.        ]
 [0.         0.         0.12060632 0.01968107]
 [0.         0.         0.27022815 0.        ]
 [0.         0.35893379 0.67311284 0.        ]
 [0.         

In [30]:
feature_representations = {node: np.array(output)[node] for node in zkc.nodes()}

In [31]:
print(feature_representations)

{0: array([0.35097244, 0.05030725]), 1: array([0.33685319, 0.        ]), 2: array([0.42339331, 0.        ]), 3: array([0.36324783, 0.        ]), 4: array([0.16533602, 0.15748014]), 5: array([0.25976117, 0.3890822 ]), 6: array([0.19561321, 0.37062285]), 7: array([0.37839806, 0.        ]), 8: array([0.38990598, 0.        ]), 9: array([0.99603504, 0.        ]), 10: array([0.10344954, 0.02976886]), 11: array([0.65116426, 0.18738038]), 12: array([0.26357892, 0.00841095]), 13: array([0.4747965, 0.       ]), 14: array([0.56479331, 0.03804311]), 15: array([0.6424106 , 0.13580133]), 16: array([0.29500256, 0.60877852]), 17: array([0.17803348, 0.        ]), 18: array([0.41721888, 0.        ]), 19: array([0.37282562, 0.        ]), 20: array([0.7086104 , 0.21757892]), 21: array([0.35556573, 0.        ]), 22: array([0.37464261, 0.        ]), 23: array([0.52152335, 0.18713232]), 24: array([0.54731846, 0.24106769]), 25: array([0.6657625 , 0.27515139]), 26: array([0.69999667, 0.08019447]), 27: array([0